#ifndef __TOKEN_TYPES_HEADER__
#define __TOKEN_TYPES_HEADER__

#define STRING_TYPE 100

#define VARIABLE_TOKEN 200
#define INTEGER_TOKEN 201
#define ASSIGNMENT_OP_TOKEN 202
#define STATEMENT_END_TOKEN 203
#define ADDITION_ARITHMETIC_TOKEN 204
#define SUBTRACTION_ARITHMETIC_TOKEN 205
#define BRACKET_OPEN_TOKEN 206
#define BRACKET_CLOSE_TOKEN 207
#define IF_KEYWORD_TOKEN 208
#define BRACE_OPEN_TOKEN 209
#define EQUALITY_OP_TOKEN 210

#endif
